!virgin
overwrite: false
verbose: false
password: PASSWORD
username: USERNAME
baseDir: /tmp/
filenamePattern: VirginBill-{1}-{0}.pdf
---
!eonenergy
username: USERNAME
password: PASSWORD
filenamePattern: EonBill-{1}-{0}.pdf

